ignore:
  - "tests/*"
  - "*.md"
  - "*.yml"
  - "*.yaml"
  - "*.json"
  - "*.toml"
  - "*.log"
  - "*.txt"
  - "*.html"
  - "**/setup.py"
  - "**/DGAmore.py"
  - "**/plotting.py"
  - "**/config_parser.py"
  - "**/symmetrize_new.py"
  - "**/mpi_distributor.py"
  - "**/mpi_utils.py"
  - "**/ana_cont.py"
  - "**/max_ent.py"
  - "**/dmft_interface.py"

coverage:
  status:
    project:
      default:
        threshold: 0%
        informational: true
    patch:
      default:
        target: 85%
        threshold: 0%
        informational: true
comment:
  layout: "reach, diff, flags, files"
  behavior: default
